# Entregable 2: Windows Defender detector

## 1. Importación de librerías, primera visualización de dataframe, comprobación de duplicados y target = "HasDetections"

In [134]:
# IMPORTAMOS LIBRERÍAS

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, MinMaxScaler

In [61]:
csv_path = r"D:\Documentos\Nuclio\Entregable_2\sample_mmp.csv"
df = pd.read_csv(csv_path, dtype={"PuaMode": 'category', "Census_ProcessorClass": "category"})

In [62]:
df.shape

(500000, 84)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 84 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Unnamed: 0                                         500000 non-null  int64
 1   MachineIdentifier                                  500000 non-null  object
 2   ProductName                                        500000 non-null  object
 3   EngineVersion                                      500000 non-null  object
 4   AppVersion                                         500000 non-null  object
 5   AvSigVersion                                       500000 non-null  object
 6   IsBeta                                             500000 non-null  int64
 7   RtpStateBitfield                                   498168 non-null  float64
 8   IsSxsPassiveMode                                   500000 non-null  int64
 9   DefaultBrowsersIdentifier                          24061 non-null   float64
 10  AVProductStatesIdentifier                          498062 non-null  float64
 11  AVProductsInstalled                                498062 non-null  float64
 12  AVProductsEnabled                                  498062 non-null  float64
 13  HasTpm                                             500000 non-null  int64
 14  CountryIdentifier                                  500000 non-null  int64
 15  CityIdentifier                                     481760 non-null  float64
 16  OrganizationIdentifier                             345437 non-null  float64
 17  GeoNameIdentifier                                  499984 non-null  float64
 18  LocaleEnglishNameIdentifier                        500000 non-null  int64
 19  Platform                                           500000 non-null  object
 20  Processor                                          500000 non-null  object
 21  OsVer                                              500000 non-null  object
 22  OsBuild                                            500000 non-null  int64
 23  OsSuite                                            500000 non-null  int64
 24  OsPlatformSubRelease                               500000 non-null  object
 25  OsBuildLab                                         499999 non-null  object
 26  SkuEdition                                         500000 non-null  object
 27  IsProtected                                        498074 non-null  float64
 28  AutoSampleOptIn                                    500000 non-null  int64
 29  PuaMode                                            126 non-null     category
 30  SMode                                              470152 non-null  float64
 31  IeVerIdentifier                                    496791 non-null  float64
 32  SmartScreen                                        321404 non-null  object
 33  Firewall                                           494838 non-null  float64
 34  UacLuaenable                                       499377 non-null  float64
 35  Census_MDC2FormFactor                              500000 non-null  object
 36  Census_DeviceFamily                                500000 non-null  object
 37  Census_OEMNameIdentifier                           494619 non-null  float64
 38  Census_OEMModelIdentifier                          494236 non-null  float64
 39  Census_ProcessorCoreCount                          497653 non-null  float64
 40  Census_ProcessorManufacturerIdentifier             497653 non-null  float64
 41  Census_ProcessorModelIdentifier                    497651 non-null  float64
 42  Census_ProcessorClass                              2082 non-null    category
 43  Census_PrimaryDiskTotalCapacity                    497024 non-null  float64
 44  Census_PrimaryDiskTypeName                         499291 non-null  object
 45  Census_SystemVolumeTotalCapacity                   497024 non-null  float64
 46  Census_HasOpticalDiskDrive                         500000 non-null  int64
 47  Census_TotalPhysicalRAM                            495444 non-null  float64
 48  Census_ChassisTypeName                             499963 non-null  object
 49  Census_InternalPrimaryDiagonalDisplaySizeInInches  497346 non-null  float64
 50  Census_InternalPrimaryDisplayResolutionHorizontal  497350 non-null  float64
 51  Census_InternalPrimaryDisplayResolutionVertical    497350 non-null  float64
 52  Census_PowerPlatformRoleName                       499998 non-null  object
 53  Census_InternalBatteryType                         144397 non-null  object
 54  Census_InternalBatteryNumberOfCharges              484962 non-null  float64
 55  Census_OSVersion                                   500000 non-null  object
 56  Census_OSArchitecture                              500000 non-null  object
 57  Census_OSBranch                                    500000 non-null  object
 58  Census_OSBuildNumber                               500000 non-null  int64
 59  Census_OSBuildRevision                             500000 non-null  int64
 60  Census_OSEdition                                   500000 non-null  object
 61  Census_OSSkuName                                   500000 non-null  object
 62  Census_OSInstallTypeName                           500000 non-null  object
 63  Census_OSInstallLanguageIdentifier                 496668 non-null  float64
 64  Census_OSUILocaleIdentifier                        500000 non-null  int64
 65  Census_OSWUAutoUpdateOptionsName                   500000 non-null  object
 66  Census_IsPortableOperatingSystem                   500000 non-null  int64
 67  Census_GenuineStateName                            500000 non-null  object
 68  Census_ActivationChannel                           500000 non-null  object
 69  Census_IsFlightingInternal                         84775 non-null   float64
 70  Census_IsFlightsDisabled                           491067 non-null  float64
 71  Census_FlightRing                                  500000 non-null  object
 72  Census_ThresholdOptIn                              181896 non-null  float64
 73  Census_FirmwareManufacturerIdentifier              489651 non-null  float64
 74  Census_FirmwareVersionIdentifier                   490939 non-null  float64
 75  Census_IsSecureBootEnabled                         500000 non-null  int64
 76  Census_IsWIMBootEnabled                            182334 non-null  float64
 77  Census_IsVirtualDevice                             499099 non-null  float64
 78  Census_IsTouchEnabled                              500000 non-null  int64
 79  Census_IsPenCapable                                500000 non-null  int64
 80  Census_IsAlwaysOnAlwaysConnectedCapable            495960 non-null  float64
 81  Wdft_IsGamer                                       483050 non-null  float64
 82  Wdft_RegionIdentifier                              483050 non-null  float64
 83  HasDetections                                      500000 non-null  int64
dtypes: category(2), float64(36), int64(18), object(28)
memory usage: 313.8+ MB

In [64]:
df.head().T

,0,1,2,3,4
Unnamed: 0,8427007,8829090,2731904,1359513,236059
MachineIdentifier,f1cd864e97bae82bdf96523e1a539121,fd5ba6f5b75325ec0423a6c67cc75942,4e628391e7cc7c482fb3286f486dbd25,270a2e9d028144a4df12a9e3da79fba5,06ca8fa8d32c2abdc5b3577d676b3269
ProductName,win8defender,win8defender,win8defender,win8defender,win8defender
EngineVersion,1.1.15100.1,1.1.15100.1,1.1.15100.1,1.1.15200.1,1.1.15200.1
AppVersion,4.18.1807.18075,4.18.1807.18075,4.9.10586.1106,4.18.1807.18075,4.18.1807.18075
AvSigVersion,1.273.1234.0,1.273.1282.0,1.273.781.0,1.275.1639.0,1.275.511.0
IsBeta,0,0,0,0,0
RtpStateBitfield,7.0,7.0,7.0,7.0,7.0
IsSxsPassiveMode,0,0,0,0,0
DefaultBrowsersIdentifier,NaN,NaN,NaN,NaN,NaN
AVProductStatesIdentifier,53447.0,53447.0,46781.0,53447.0,47238.0
AVProductsInstalled,1.0,1.0,2.0,1.0,2.0
AVProductsEnabled,1.0,1.0,1.0,1.0,1.0
HasTpm,1,1,1,1,1
CountryIdentifier,8,129,149,164,207
CityIdentifier,85219.0,54198.0,122689.0,114587.0,72421.0
OrganizationIdentifier,NaN,NaN,27.0,27.0,27.0
GeoNameIdentifier,205.0,126.0,181.0,205.0,277.0
LocaleEnglishNameIdentifier,172,124,56,172,75
Platform,windows10,windows10,windows10,windows10,windows10
Processor,x64,x64,x64,x64,x64
OsVer,10.0.0.0,10.0.0.0,10.0.0.0,10.0.0.0,10.0.0.0
OsBuild,17134,17134,10586,17134,17134
OsSuite,256,256,768,768,256
OsPlatformSubRelease,rs4,rs4,th2,rs4,rs4
OsBuildLab,17134.1.amd64fre.rs4_release.180410-1804,17134.1.amd64fre.rs4_release.180410-1804,10586.1176.amd64fre.th2_release_sec.170913-1848,17134.1.amd64fre.rs4_release.180410-1804,17134.1.amd64fre.rs4_release.180410-1804
SkuEdition,Pro,Pro,Home,Home,Pro
IsProtected,1.0,1.0,1.0,1.0,1.0
AutoSampleOptIn,0,0,0,0,0
PuaMode,NaN,NaN,NaN,NaN,NaN
SMode,0.0,0.0,0.0,0.0,0.0
IeVerIdentifier,137.0,137.0,74.0,137.0,137.0
SmartScreen,RequireAdmin,RequireAdmin,RequireAdmin,NaN,RequireAdmin
Firewall,1.0,1.0,1.0,1.0,1.0
UacLuaenable,1.0,1.0,1.0,1.0,1.0
Census_MDC2FormFactor,Desktop,Notebook,Convertible,Notebook,Notebook
Census_DeviceFamily,Windows.Desktop,Windows.Desktop,Windows.Desktop,Windows.Desktop,Windows.Desktop
Census_OEMNameIdentifier,1443.0,2102.0,2206.0,525.0,1443.0
Census_OEMModelIdentifier,275891.0,248850.0,238234.0,265410.0,256478.0
Census_ProcessorCoreCount,4.0,4.0,4.0,8.0,4.0
Census_ProcessorManufacturerIdentifier,5.0,5.0,5.0,5.0,1.0
Census_ProcessorModelIdentifier,2273.0,2660.0,2998.0,2880.0,198.0
Census_ProcessorClass,NaN,NaN,NaN,NaN,NaN
Census_PrimaryDiskTotalCapacity,953869.0,476940.0,244198.0,228936.0,476940.0
Census_PrimaryDiskTypeName,HDD,HDD,SSD,SSD,HDD
Census_SystemVolumeTotalCapacity,952838.0,457600.0,221251.0,228321.0,464374.0
Census_HasOpticalDiskDrive,0,0,0,0,0
Census_TotalPhysicalRAM,8192.0,8192.0,8192.0,8192.0,4096.0
Census_ChassisTypeName,AllinOne,Notebook,Notebook,Notebook,Portable
Census_InternalPrimaryDiagonalDisplaySizeInInches,23.0,13.2,15.5,15.5,15.5
Census_InternalPrimaryDisplayResolutionHorizontal,1920.0,1280.0,1920.0,1920.0,1366.0
Census_InternalPrimaryDisplayResolutionVertical,1080.0,720.0,1080.0,1080.0,768.0
Census_PowerPlatformRoleName,Desktop,Mobile,Mobile,Mobile,Mobile
Census_InternalBatteryType,NaN,lion,lion,NaN,NaN
Census_InternalBatteryNumberOfCharges,4294967295.0,0.0,0.0,577.0,0.0
Census_OSVersion,10.0.17134.165,10.0.17134.165,10.0.10586.1176,10.0.17134.286,10.0.17134.228
Census_OSArchitecture,amd64,amd64,amd64,amd64,amd64
Census_OSBranch,rs4_release,rs4_release,th2_release_sec,rs4_release,rs4_release
Census_OSBuildNumber,17134,17134,10586,17134,17134
Census_OSBuildRevision,165,165,1176,286,228
Census_OSEdition,Professional,Professional,Core,Core,Professional
Census_OSSkuName,PROFESSIONAL,PROFESSIONAL,CORE,CORE,PROFESSIONAL
Census_OSInstallTypeName,UUPUpgrade,UUPUpgrade,Update,IBSClean,Update
Census_OSInstallLanguageIdentifier,27.0,18.0,24.0,27.0,8.0
Census_OSUILocaleIdentifier,120,72,109,120,31
Census_OSWUAutoUpdateOptionsName,FullAuto,FullAuto,Notify,FullAuto,FullAuto
Census_IsPortableOperatingSystem,0,0,0,0,0
Census_GenuineStateName,IS_GENUINE,IS_GENUINE,IS_GENUINE,IS_GENUINE,IS_GENUINE
Census_ActivationChannel,OEM:DM,OEM:DM,Retail,Retail,OEM:DM
Census_IsFlightingInternal,NaN,NaN,NaN,NaN,NaN
Census_IsFlightsDisabled,0.0,0.0,0.0,0.0,0.0
Census_FlightRing,Retail,Retail,Retail,Retail,Retail
Census_ThresholdOptIn,NaN,0.0,0.0,NaN,NaN
Census_FirmwareManufacturerIdentifier,355.0,486.0,554.0,142.0,355.0
Census_FirmwareVersionIdentifier,19951.0,48753.0,33111.0,48473.0,4343.0
Census_IsSecureBootEnabled,0,0,1,1,1
Census_IsWIMBootEnabled,NaN,0.0,0.0,NaN,NaN
Census_IsVirtualDevice,0.0,0.0,0.0,0.0,0.0
Census_IsTouchEnabled,0,0,1,0,1
Census_IsPenCapable,0,0,1,0,0
Census_IsAlwaysOnAlwaysConnectedCapable,0.0,0.0,0.0,0.0,0.0
Wdft_IsGamer,0.0,1.0,0.0,0.0,1.0
Wdft_RegionIdentifier,11.0,3.0,15.0,15.0,13.0
HasDetections,1,0,0,1,1

In [65]:
pd.set_option('display.max_rows', 100)

In [66]:
numeric_describe = df.describe(include='number').T
numeric_describe

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,500000.0,4.458888e+06,2.575619e+06,2.0,2227692.50,4461367.5,6.690936e+06,8.921471e+06
IsBeta,500000.0,2.000000e-06,1.414214e-03,0.0,0.00,0.0,0.000000e+00,1.000000e+00
RtpStateBitfield,498168.0,6.846207e+00,1.023049e+00,0.0,7.00,7.0,7.000000e+00,3.500000e+01
IsSxsPassiveMode,500000.0,1.724200e-02,1.301720e-01,0.0,0.00,0.0,0.000000e+00,1.000000e+00
DefaultBrowsersIdentifier,24061.0,1.652825e+03,1.004754e+03,1.0,788.00,1632.0,2.381000e+03,3.209000e+03
AVProductStatesIdentifier,498062.0,4.785091e+04,1.402309e+04,3.0,49480.00,53447.0,5.344700e+04,7.049200e+04
AVProductsInstalled,498062.0,1.326763e+00,5.229999e-01,1.0,1.00,1.0,2.000000e+00,5.000000e+00
AVProductsEnabled,498062.0,1.020714e+00,1.666080e-01,0.0,1.00,1.0,1.000000e+00,4.000000e+00
HasTpm,500000.0,9.878160e-01,1.097068e-01,0.0,1.00,1.0,1.000000e+00,1.000000e+00
CountryIdentifier,500000.0,1.080375e+02,6.306854e+01,1.0,51.00,97.0,1.620000e+02,2.220000e+02
CityIdentifier,481760.0,8.127165e+04,4.898513e+04,7.0,36825.00,82373.0,1.239395e+05,1.679580e+05
OrganizationIdentifier,345437.0,2.486994e+01,5.613712e+00,1.0,18.00,27.0,2.700000e+01,5.200000e+01
GeoNameIdentifier,499984.0,1.697304e+02,8.932517e+01,1.0,89.00,181.0,2.670000e+02,2.960000e+02
LocaleEnglishNameIdentifier,500000.0,1.226110e+02,6.930317e+01,1.0,74.00,88.0,1.820000e+02,2.830000e+02
OsBuild,500000.0,1.572693e+04,2.188646e+03,7600.0,15063.00,16299.0,1.713400e+04,1.824200e+04
OsSuite,500000.0,5.747186e+02,2.482033e+02,16.0,256.00,768.0,7.680000e+02,7.840000e+02
IsProtected,498074.0,9.457892e-01,2.264335e-01,0.0,1.00,1.0,1.000000e+00,1.000000e+00
AutoSampleOptIn,500000.0,2.800000e-05,5.291434e-03,0.0,0.00,0.0,0.000000e+00,1.000000e+00
SMode,470152.0,4.381562e-04,2.092762e-02,0.0,0.00,0.0,0.000000e+00,1.000000e+00
IeVerIdentifier,496791.0,1.266626e+02,4.263489e+01,8.0,111.00,135.0,1.370000e+02,4.290000e+02
Firewall,494838.0,9.782414e-01,1.458946e-01,0.0,1.00,1.0,1.000000e+00,1.000000e+00
UacLuaenable,499377.0,1.372503e+01,8.995848e+03,0.0,1.00,1.0,1.000000e+00,6.357062e+06
Census_OEMNameIdentifier,494619.0,2.218646e+03,1.315710e+03,54.0,1443.00,2102.0,2.668000e+03,6.143000e+03
Census_OEMModelIdentifier,494236.0,2.391280e+05,7.204888e+04,1.0,189641.75,247520.0,3.044380e+05,3.454930e+05
Census_ProcessorCoreCount,497653.0,3.994074e+00,2.071281e+00,1.0,2.00,4.0,4.000000e+00,8.800000e+01
Census_ProcessorManufacturerIdentifier,497653.0,4.529069e+00,1.289635e+00,1.0,5.00,5.0,5.000000e+00,1.000000e+01
Census_ProcessorModelIdentifier,497651.0,2.370987e+03,8.421367e+02,3.0,1998.00,2500.0,2.877000e+03,4.472000e+03
Census_PrimaryDiskTotalCapacity,497024.0,5.140433e+05,3.704468e+05,10240.0,239372.00,476940.0,9.538690e+05,4.768767e+07
Census_SystemVolumeTotalCapacity,497024.0,3.780546e+05,3.384722e+05,9689.0,120775.00,249450.0,4.759810e+05,4.768710e+07
Census_HasOpticalDiskDrive,500000.0,7.703400e-02,2.666457e-01,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_TotalPhysicalRAM,495444.0,6.129232e+03,4.964521e+03,512.0,4096.00,4096.0,8.192000e+03,3.932160e+05
Census_InternalPrimaryDiagonalDisplaySizeInInches,497346.0,1.668984e+01,5.932014e+00,4.9,13.90,15.5,1.720000e+01,1.420000e+02
Census_InternalPrimaryDisplayResolutionHorizontal,497350.0,1.548304e+03,3.685659e+02,-1.0,1366.00,1366.0,1.920000e+03,1.152000e+04
Census_InternalPrimaryDisplayResolutionVertical,497350.0,8.982393e+02,2.148625e+02,-1.0,768.00,768.0,1.080000e+03,4.320000e+03
Census_InternalBatteryNumberOfCharges,484962.0,1.125600e+09,1.888768e+09,0.0,0.00,0.0,4.294967e+09,4.294967e+09
Census_OSBuildNumber,500000.0,1.584137e+04,1.959440e+03,9600.0,15063.00,16299.0,1.713400e+04,1.824200e+04
Census_OSBuildRevision,500000.0,9.672248e+02,2.920628e+03,0.0,165.00,285.0,5.470000e+02,1.906900e+04
Census_OSInstallLanguageIdentifier,496668.0,1.460551e+01,1.020095e+01,1.0,8.00,9.0,2.000000e+01,3.900000e+01
Census_OSUILocaleIdentifier,500000.0,6.044631e+01,4.500042e+01,1.0,31.00,34.0,9.000000e+01,1.620000e+02
Census_IsPortableOperatingSystem,500000.0,5.220000e-04,2.284138e-02,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_IsFlightingInternal,84775.0,2.359186e-05,4.857117e-03,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_IsFlightsDisabled,491067.0,1.425467e-05,3.775513e-03,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_ThresholdOptIn,181896.0,2.583894e-04,1.607246e-02,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_FirmwareManufacturerIdentifier,489651.0,4.026759e+02,2.215271e+02,11.0,142.00,500.0,5.560000e+02,1.084000e+03
Census_FirmwareVersionIdentifier,490939.0,3.303099e+04,2.122016e+04,10.0,13156.00,33070.0,5.243600e+04,7.209100e+04
Census_IsSecureBootEnabled,500000.0,4.854380e-01,4.997884e-01,0.0,0.00,0.0,1.000000e+00,1.000000e+00
Census_IsWIMBootEnabled,182334.0,0.000000e+00,0.000000e+00,0.0,0.00,0.0,0.000000e+00,0.000000e+00
Census_IsVirtualDevice,499099.0,7.066734e-03,8.376640e-02,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_IsTouchEnabled,500000.0,1.254340e-01,3.312107e-01,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_IsPenCapable,500000.0,3.774400e-02,1.905767e-01,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Census_IsAlwaysOnAlwaysConnectedCapable,495960.0,5.724454e-02,2.323095e-01,0.0,0.00,0.0,0.000000e+00,1.000000e+00
Wdft_IsGamer,483050.0,2.840596e-01,4.509658e-01,0.0,0.00,0.0,1.000000e+00,1.000000e+00
Wdft_RegionIdentifier,483050.0,7.888577e+00,4.551764e+00,1.0,3.00,10.0,1.100000e+01,1.500000e+01
HasDetections,500000.0,4.999060e-01,5.000005e-01,0.0,0.00,0.0,1.000000e+00,1.000000e+00

In [67]:
object_describe = df.describe(include='object').T
object_describe

,count,unique,top,freq
MachineIdentifier,500000,500000,fba7138931e22f004ee389c236b98254,1
ProductName,500000,3,win8defender,494604
EngineVersion,500000,53,1.1.15200.1,216491
AppVersion,500000,95,4.18.1807.18075,288809
AvSigVersion,500000,6455,1.273.1420.0,5771
Platform,500000,4,windows10,483048
Processor,500000,3,x64,454423
OsVer,500000,21,10.0.0.0,483830
OsPlatformSubRelease,500000,9,rs4,220779
OsBuildLab,499999,453,17134.1.amd64fre.rs4_release.180410-1804,206436
SkuEdition,500000,8,Home,308567
SmartScreen,321404,12,RequireAdmin,241594
Census_MDC2FormFactor,500000,12,Notebook,320948
Census_DeviceFamily,500000,3,Windows.Desktop,499183
Census_PrimaryDiskTypeName,499291,4,HDD,325429
Census_ChassisTypeName,499963,34,Notebook,294232
Census_PowerPlatformRoleName,499998,9,Mobile,346378
Census_InternalBatteryType,144397,28,lion,113500
Census_OSVersion,500000,305,10.0.17134.228,79975
Census_OSArchitecture,500000,3,amd64,454435
Census_OSBranch,500000,15,rs4_release,226001
Census_OSEdition,500000,22,Core,194469
Census_OSSkuName,500000,21,CORE,194464
Census_OSInstallTypeName,500000,9,UUPUpgrade,146780
Census_OSWUAutoUpdateOptionsName,500000,6,FullAuto,222482
Census_GenuineStateName,500000,4,IS_GENUINE,441402
Census_ActivationChannel,500000,6,Retail,264932
Census_FlightRing,500000,8,Retail,468299

In [68]:
df[df.duplicated(keep="first")]

Empty DataFrame
Columns: [Unnamed: 0, MachineIdentifier, ProductName, EngineVersion, AppVersion, AvSigVersion, IsBeta, RtpStateBitfield, IsSxsPassiveMode, DefaultBrowsersIdentifier, AVProductStatesIdentifier, AVProductsInstalled, AVProductsEnabled, HasTpm, CountryIdentifier, CityIdentifier, OrganizationIdentifier, GeoNameIdentifier, LocaleEnglishNameIdentifier, Platform, Processor, OsVer, OsBuild, OsSuite, OsPlatformSubRelease, OsBuildLab, SkuEdition, IsProtected, AutoSampleOptIn, PuaMode, SMode, IeVerIdentifier, SmartScreen, Firewall, UacLuaenable, Census_MDC2FormFactor, Census_DeviceFamily, Census_OEMNameIdentifier, Census_OEMModelIdentifier, Census_ProcessorCoreCount, Census_ProcessorManufacturerIdentifier, Census_ProcessorModelIdentifier, Census_ProcessorClass, Census_PrimaryDiskTotalCapacity, Census_PrimaryDiskTypeName, Census_SystemVolumeTotalCapacity, Census_HasOpticalDiskDrive, Census_TotalPhysicalRAM, Census_ChassisTypeName, Census_InternalPrimaryDiagonalDisplaySizeInInches, Census_InternalPrimaryDisplayResolutionHorizontal, Census_InternalPrimaryDisplayResolutionVertical, Census_PowerPlatformRoleName, Census_InternalBatteryType, Census_InternalBatteryNumberOfCharges, Census_OSVersion, Census_OSArchitecture, Census_OSBranch, Census_OSBuildNumber, Census_OSBuildRevision, Census_OSEdition, Census_OSSkuName, Census_OSInstallTypeName, Census_OSInstallLanguageIdentifier, Census_OSUILocaleIdentifier, Census_OSWUAutoUpdateOptionsName, Census_IsPortableOperatingSystem, Census_GenuineStateName, Census_ActivationChannel, Census_IsFlightingInternal, Census_IsFlightsDisabled, Census_FlightRing, Census_ThresholdOptIn, Census_FirmwareManufacturerIdentifier, Census_FirmwareVersionIdentifier, Census_IsSecureBootEnabled, Census_IsWIMBootEnabled, Census_IsVirtualDevice, Census_IsTouchEnabled, Census_IsPenCapable, Census_IsAlwaysOnAlwaysConnectedCapable, Wdft_IsGamer, Wdft_RegionIdentifier, HasDetections]
Index: []

[0 rows x 84 columns]

In [69]:
df.isna().sum()

Unnamed: 0                                                0
MachineIdentifier                                         0
ProductName                                               0
EngineVersion                                             0
AppVersion                                                0
AvSigVersion                                              0
IsBeta                                                    0
RtpStateBitfield                                       1832
IsSxsPassiveMode                                          0
DefaultBrowsersIdentifier                            475939
AVProductStatesIdentifier                              1938
AVProductsInstalled                                    1938
AVProductsEnabled                                      1938
HasTpm                                                    0
CountryIdentifier                                         0
CityIdentifier                                        18240
OrganizationIdentifier                               154563
GeoNameIdentifier                                        16
LocaleEnglishNameIdentifier                               0
Platform                                                  0
Processor                                                 0
OsVer                                                     0
OsBuild                                                   0
OsSuite                                                   0
OsPlatformSubRelease                                      0
OsBuildLab                                                1
SkuEdition                                                0
IsProtected                                            1926
AutoSampleOptIn                                           0
PuaMode                                              499874
SMode                                                 29848
IeVerIdentifier                                        3209
SmartScreen                                          178596
Firewall                                               5162
UacLuaenable                                            623
Census_MDC2FormFactor                                     0
Census_DeviceFamily                                       0
Census_OEMNameIdentifier                               5381
Census_OEMModelIdentifier                              5764
Census_ProcessorCoreCount                              2347
Census_ProcessorManufacturerIdentifier                 2347
Census_ProcessorModelIdentifier                        2349
Census_ProcessorClass                                497918
Census_PrimaryDiskTotalCapacity                        2976
Census_PrimaryDiskTypeName                              709
Census_SystemVolumeTotalCapacity                       2976
Census_HasOpticalDiskDrive                                0
Census_TotalPhysicalRAM                                4556
Census_ChassisTypeName                                   37
Census_InternalPrimaryDiagonalDisplaySizeInInches      2654
Census_InternalPrimaryDisplayResolutionHorizontal      2650
Census_InternalPrimaryDisplayResolutionVertical        2650
Census_PowerPlatformRoleName                              2
Census_InternalBatteryType                           355603
Census_InternalBatteryNumberOfCharges                 15038
Census_OSVersion                                          0
Census_OSArchitecture                                     0
Census_OSBranch                                           0
Census_OSBuildNumber                                      0
Census_OSBuildRevision                                    0
Census_OSEdition                                          0
Census_OSSkuName                                          0
Census_OSInstallTypeName                                  0
Census_OSInstallLanguageIdentifier                     3332
Census_OSUILocaleIdentifier                               0
Census_OSWUAutoUpdateOptionsName                          0
Census_IsPortableOperatingSystem                          0
Census_GenuineStateName                                   0
Census_ActivationChannel                                  0
Census_IsFlightingInternal                           415225
Census_IsFlightsDisabled                               8933
Census_FlightRing                                         0
Census_ThresholdOptIn                                318104
Census_FirmwareManufacturerIdentifier                 10349
Census_FirmwareVersionIdentifier                       9061
Census_IsSecureBootEnabled                                0
Census_IsWIMBootEnabled                              317666
Census_IsVirtualDevice                                  901
Census_IsTouchEnabled                                     0
Census_IsPenCapable                                       0
Census_IsAlwaysOnAlwaysConnectedCapable                4040
Wdft_IsGamer                                          16950
Wdft_RegionIdentifier                                 16950
HasDetections                                             0
dtype: int64

In [70]:
df.drop(columns = ['Unnamed: 0', 'MachineIdentifier'], axis=1, inplace=True)

### 1.1. Definición de target y ajuste de tipo de variables

In [71]:
target = "HasDetections"

In [72]:
df['OrganizationIdentifier'] = df['OrganizationIdentifier'].astype('category')

## 2. Separación validación, test y train

Se empleará el método stratification para mantener la distribución del target ya que está balanceado

In [73]:
from sklearn.model_selection import train_test_split

X = df.drop(target, axis=1)
y = df[target]

# Step 1: Create Validation set (15%)
X_temp, X_val, y_temp, y_val = train_test_split(
    X, y,
    test_size=75000,  # 15% of total
    stratify=y,
    random_state=42
)

# Step 2: Create TEST set (15% of total)

X_train, X_test, y_train, y_test = train_test_split(
    X_temp, y_temp,
    test_size=75000, # 15% of total
    stratify=y_temp,
    random_state=42
)

In [74]:
print("Train:", y_train.value_counts(normalize=True))
print("Val:", y_val.value_counts(normalize=True))
print("Test:", y_test.value_counts(normalize=True))

Train: HasDetections
0    0.500094
1    0.499906
Name: proportion, dtype: float64
Val: HasDetections
0    0.500093
1    0.499907
Name: proportion, dtype: float64
Test: HasDetections
0    0.500093
1    0.499907
Name: proportion, dtype: float64

In [75]:
np.save("train_idx.npy", X_train.index)
np.save("val_idx.npy", X_val.index)
np.save("test_idx.npy", X_test.index)

In [76]:
df_train = X_train.copy()
df_train[target] = y_train

## 3. EDA + Gestión de nulos

In [113]:
numeric_features = X_train.select_dtypes(include=np.number).columns.tolist()
categorical_features = X_train.select_dtypes(include=["object", "category"]).columns.tolist()

In [127]:
class EDAInspector:
    
    def __init__(self, df):
        self.df = df
        self.refresh_types()
    
    
    # ----------------------------
    # TYPE REFRESH
    # ----------------------------
    
    def refresh_types(self):
        self.n_rows = len(self.df)
        self.numeric_cols = self.df.select_dtypes(include=np.number).columns.tolist()
        self.object_cols = self.df.select_dtypes(include=["object"]).columns.tolist()
        self.category_cols = self.df.select_dtypes(include=["category"]).columns.tolist()
        self.bool_cols = self.df.select_dtypes(include=["bool"]).columns.tolist()
    
    
    # ----------------------------
    # NUMERIC SUMMARY
    # ----------------------------
    
    def numeric_summary(self):
        
        summary = pd.DataFrame({
            "dtype": self.df[self.numeric_cols].dtypes,
            "unique_values": self.df[self.numeric_cols].nunique(),
            "pct_unique": self.df[self.numeric_cols].nunique() / self.n_rows * 100,
            "null_pct": self.df[self.numeric_cols].isnull().mean() * 100,
            "min": self.df[self.numeric_cols].min(),
            "max": self.df[self.numeric_cols].max()
        })
        
        summary["possible_id"] = summary["pct_unique"] > 90
        
        summary["likely_categorical"] = (
            (summary["unique_values"] < 50) &
            (summary["pct_unique"] < 5)
        )
        
        return summary.sort_values("pct_unique", ascending=False)
    
    
    # ----------------------------
    # CATEGORICAL SUMMARY
    # ----------------------------
    
    def categorical_summary(self):
        
        cat_cols = self.object_cols + self.category_cols
        
        summary = pd.DataFrame({
            "dtype": self.df[cat_cols].dtypes,
            "unique_values": self.df[cat_cols].nunique(),
            "pct_unique": self.df[cat_cols].nunique() / self.n_rows * 100,
            "null_pct": self.df[cat_cols].isnull().mean() * 100
        })
        
        summary["high_cardinality"] = summary["unique_values"] > 100
        
        return summary.sort_values("unique_values", ascending=False)
    
    # ----------------------------
    # Identifier/Version etc DETECTOR in numeric columns
    # ---------------------------- 
    
    def detect_identifier_columns(self, keywords=None):
    
        if keywords is None:
            keywords = ["identifier"]
        
        self.identifier_cols = [
            col for col in self.numeric_cols
            if any(k in col.lower() for k in keywords)
        ]
        
        print(f"Detected {len(self.identifier_cols)} identifier columns:")
        #print(self.identifier_cols)
        
        return self.identifier_cols
 
    
    # ----------------------------
    # CONVERT NUMERIC → CATEGORY
    # ----------------------------
    
    def convert_to_category(self, columns, verbose=True):
        
        if isinstance(columns, str):
            columns = [columns]
        
        for col in columns:
            if col in self.df.columns:
                self.df[col] = self.df[col].astype("category")
        
        self.refresh_types()
        
        if verbose:
            print("Converted to category:", columns)
    
    
    # ----------------------------
    # CONVERT TO NUMERIC
    # ----------------------------
    
    def convert_to_numeric(self, columns, verbose=True):
        
        if isinstance(columns, str):
            columns = [columns]
        
        for col in columns:
            if col in self.df.columns:
                self.df[col] = pd.to_numeric(self.df[col], errors="coerce")
        
        self.refresh_types()
        
        if verbose:
            print("Converted to numeric:", columns)

In [128]:
inspector1 = EDAInspector(df_train)

In [129]:
inspector1.numeric_summary()

,dtype,unique_values,pct_unique,null_pct,min,max,possible_id,likely_categorical
Census_SystemVolumeTotalCapacity,float64,112810,32.231429,0.595143,9689.0,2.859558e+07,False,False
Census_OEMModelIdentifier,float64,33296,9.513143,1.150000,22.0,3.454930e+05,False,False
CityIdentifier,float64,31181,8.908857,3.626000,7.0,1.679580e+05,False,False
Census_FirmwareVersionIdentifier,float64,20897,5.970571,1.812857,10.0,7.209100e+04,False,False
AVProductStatesIdentifier,float64,4466,1.276000,0.386000,3.0,7.049200e+04,False,False
Census_InternalBatteryNumberOfCharges,float64,4031,1.151714,3.003143,0.0,4.294967e+09,False,False
Census_ProcessorModelIdentifier,float64,2127,0.607714,0.469143,19.0,4.472000e+03,False,False
Census_OEMNameIdentifier,float64,1406,0.401714,1.068571,74.0,6.143000e+03,False,False
Census_PrimaryDiskTotalCapacity,float64,906,0.258857,0.595143,10240.0,2.859591e+07,False,False
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,483,0.138000,0.534000,4.9,1.420000e+02,False,False
DefaultBrowsersIdentifier,float64,469,0.134000,95.179143,1.0,3.209000e+03,False,False
Census_TotalPhysicalRAM,float64,449,0.128286,0.896857,512.0,3.932160e+05,False,False
Census_InternalPrimaryDisplayResolutionVertical,float64,420,0.120000,0.533429,-1.0,4.320000e+03,False,False
Census_InternalPrimaryDisplayResolutionHorizontal,float64,374,0.106857,0.533429,-1.0,1.152000e+04,False,False
Census_FirmwareManufacturerIdentifier,float64,276,0.078857,2.072571,11.0,1.084000e+03,False,False
GeoNameIdentifier,float64,263,0.075143,0.003714,1.0,2.960000e+02,False,False
Census_OSBuildRevision,int64,237,0.067714,0.000000,0.0,1.906900e+04,False,False
LocaleEnglishNameIdentifier,int64,225,0.064286,0.000000,1.0,2.830000e+02,False,False
CountryIdentifier,int64,222,0.063429,0.000000,1.0,2.220000e+02,False,False
IeVerIdentifier,float64,167,0.047714,0.637714,8.0,4.290000e+02,False,False
Census_OSUILocaleIdentifier,int64,83,0.023714,0.000000,1.0,1.620000e+02,False,False
Census_OSBuildNumber,int64,54,0.015429,0.000000,9600.0,1.824200e+04,False,False
OsBuild,int64,44,0.012571,0.000000,7600.0,1.824200e+04,False,True
Census_OSInstallLanguageIdentifier,float64,39,0.011143,0.667143,1.0,3.900000e+01,False,True
Census_ProcessorCoreCount,float64,27,0.007714,0.468571,1.0,8.800000e+01,False,True
Wdft_RegionIdentifier,float64,15,0.004286,3.414000,1.0,1.500000e+01,False,True
OsSuite,int64,9,0.002571,0.000000,16.0,7.840000e+02,False,True
RtpStateBitfield,float64,7,0.002000,0.368571,0.0,3.500000e+01,False,True
AVProductsEnabled,float64,5,0.001429,0.386000,0.0,4.000000e+00,False,True
AVProductsInstalled,float64,5,0.001429,0.386000,1.0,5.000000e+00,False,True
UacLuaenable,float64,5,0.001429,0.123143,0.0,6.357062e+06,False,True
Census_ProcessorManufacturerIdentifier,float64,4,0.001143,0.468571,1.0,1.000000e+01,False,True
HasTpm,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
AutoSampleOptIn,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
IsSxsPassiveMode,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
SMode,float64,2,0.000571,5.974286,0.0,1.000000e+00,False,True
Census_IsSecureBootEnabled,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Firewall,float64,2,0.000571,1.032857,0.0,1.000000e+00,False,True
IsProtected,float64,2,0.000571,0.384286,0.0,1.000000e+00,False,True
Census_HasOpticalDiskDrive,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsFlightsDisabled,float64,2,0.000571,1.783143,0.0,1.000000e+00,False,True
Census_IsFlightingInternal,float64,2,0.000571,83.038286,0.0,1.000000e+00,False,True
Census_ThresholdOptIn,float64,2,0.000571,63.641714,0.0,1.000000e+00,False,True
Census_IsPortableOperatingSystem,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Wdft_IsGamer,float64,2,0.000571,3.414000,0.0,1.000000e+00,False,True
Census_IsVirtualDevice,float64,2,0.000571,0.181714,0.0,1.000000e+00,False,True
Census_IsPenCapable,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsTouchEnabled,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
HasDetections,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsAlwaysOnAlwaysConnectedCapable,float64,2,0.000571,0.804000,0.0,1.000000e+00,False,True
IsBeta,int64,1,0.000286,0.000000,0.0,0.000000e+00,False,True
Census_IsWIMBootEnabled,float64,1,0.000286,63.558857,0.0,0.000000e+00,False,True

In [130]:
inspector1.detect_identifier_columns()

Detected 16 identifier columns:

['DefaultBrowsersIdentifier',
 'AVProductStatesIdentifier',
 'CountryIdentifier',
 'CityIdentifier',
 'GeoNameIdentifier',
 'LocaleEnglishNameIdentifier',
 'IeVerIdentifier',
 'Census_OEMNameIdentifier',
 'Census_OEMModelIdentifier',
 'Census_ProcessorManufacturerIdentifier',
 'Census_ProcessorModelIdentifier',
 'Census_OSInstallLanguageIdentifier',
 'Census_OSUILocaleIdentifier',
 'Census_FirmwareManufacturerIdentifier',
 'Census_FirmwareVersionIdentifier',
 'Wdft_RegionIdentifier']

In [131]:
inspector1.convert_to_category(inspector1.identifier_cols)

Converted to category: ['DefaultBrowsersIdentifier', 'AVProductStatesIdentifier', 'CountryIdentifier', 'CityIdentifier', 'GeoNameIdentifier', 'LocaleEnglishNameIdentifier', 'IeVerIdentifier', 'Census_OEMNameIdentifier', 'Census_OEMModelIdentifier', 'Census_ProcessorManufacturerIdentifier', 'Census_ProcessorModelIdentifier', 'Census_OSInstallLanguageIdentifier', 'Census_OSUILocaleIdentifier', 'Census_FirmwareManufacturerIdentifier', 'Census_FirmwareVersionIdentifier', 'Wdft_RegionIdentifier']

In [132]:
inspector1.numeric_summary()

,dtype,unique_values,pct_unique,null_pct,min,max,possible_id,likely_categorical
Census_SystemVolumeTotalCapacity,float64,112810,32.231429,0.595143,9689.0,2.859558e+07,False,False
Census_InternalBatteryNumberOfCharges,float64,4031,1.151714,3.003143,0.0,4.294967e+09,False,False
Census_PrimaryDiskTotalCapacity,float64,906,0.258857,0.595143,10240.0,2.859591e+07,False,False
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,483,0.138000,0.534000,4.9,1.420000e+02,False,False
Census_TotalPhysicalRAM,float64,449,0.128286,0.896857,512.0,3.932160e+05,False,False
Census_InternalPrimaryDisplayResolutionVertical,float64,420,0.120000,0.533429,-1.0,4.320000e+03,False,False
Census_InternalPrimaryDisplayResolutionHorizontal,float64,374,0.106857,0.533429,-1.0,1.152000e+04,False,False
Census_OSBuildRevision,int64,237,0.067714,0.000000,0.0,1.906900e+04,False,False
Census_OSBuildNumber,int64,54,0.015429,0.000000,9600.0,1.824200e+04,False,False
OsBuild,int64,44,0.012571,0.000000,7600.0,1.824200e+04,False,True
Census_ProcessorCoreCount,float64,27,0.007714,0.468571,1.0,8.800000e+01,False,True
OsSuite,int64,9,0.002571,0.000000,16.0,7.840000e+02,False,True
RtpStateBitfield,float64,7,0.002000,0.368571,0.0,3.500000e+01,False,True
UacLuaenable,float64,5,0.001429,0.123143,0.0,6.357062e+06,False,True
AVProductsInstalled,float64,5,0.001429,0.386000,1.0,5.000000e+00,False,True
AVProductsEnabled,float64,5,0.001429,0.386000,0.0,4.000000e+00,False,True
Census_HasOpticalDiskDrive,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
IsSxsPassiveMode,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Firewall,float64,2,0.000571,1.032857,0.0,1.000000e+00,False,True
IsProtected,float64,2,0.000571,0.384286,0.0,1.000000e+00,False,True
Census_IsSecureBootEnabled,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
AutoSampleOptIn,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
SMode,float64,2,0.000571,5.974286,0.0,1.000000e+00,False,True
HasTpm,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsPortableOperatingSystem,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsFlightingInternal,float64,2,0.000571,83.038286,0.0,1.000000e+00,False,True
Census_IsFlightsDisabled,float64,2,0.000571,1.783143,0.0,1.000000e+00,False,True
Census_ThresholdOptIn,float64,2,0.000571,63.641714,0.0,1.000000e+00,False,True
Wdft_IsGamer,float64,2,0.000571,3.414000,0.0,1.000000e+00,False,True
Census_IsVirtualDevice,float64,2,0.000571,0.181714,0.0,1.000000e+00,False,True
Census_IsTouchEnabled,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsPenCapable,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
HasDetections,int64,2,0.000571,0.000000,0.0,1.000000e+00,False,True
Census_IsAlwaysOnAlwaysConnectedCapable,float64,2,0.000571,0.804000,0.0,1.000000e+00,False,True
IsBeta,int64,1,0.000286,0.000000,0.0,0.000000e+00,False,True
Census_IsWIMBootEnabled,float64,1,0.000286,63.558857,0.0,0.000000e+00,False,True

In [133]:
inspector1.categorical_summary()

,dtype,unique_values,pct_unique,null_pct,high_cardinality
Census_OEMModelIdentifier,category,33296,9.513143,1.150000,True
CityIdentifier,category,31181,8.908857,3.626000,True
Census_FirmwareVersionIdentifier,category,20897,5.970571,1.812857,True
AvSigVersion,object,5925,1.692857,0.000000,True
AVProductStatesIdentifier,category,4466,1.276000,0.386000,True
Census_ProcessorModelIdentifier,category,2127,0.607714,0.469143,True
Census_OEMNameIdentifier,category,1406,0.401714,1.068571,True
DefaultBrowsersIdentifier,category,469,0.134000,95.179143,True
OsBuildLab,object,431,0.123143,0.000286,True
Census_OSVersion,object,292,0.083429,0.000000,True
Census_FirmwareManufacturerIdentifier,category,276,0.078857,2.072571,True
GeoNameIdentifier,category,263,0.075143,0.003714,True
LocaleEnglishNameIdentifier,category,225,0.064286,0.000000,True
CountryIdentifier,category,222,0.063429,0.000000,True
IeVerIdentifier,category,167,0.047714,0.637714,True
AppVersion,object,93,0.026571,0.000000,False
Census_OSUILocaleIdentifier,category,83,0.023714,0.000000,False
EngineVersion,object,52,0.014857,0.000000,False
OrganizationIdentifier,category,43,0.012286,30.939429,False
Census_OSInstallLanguageIdentifier,category,39,0.011143,0.667143,False
Census_ChassisTypeName,object,33,0.009429,0.008000,False
Census_InternalBatteryType,object,27,0.007714,71.154857,False
Census_OSEdition,object,19,0.005429,0.000000,False
Census_OSSkuName,object,18,0.005143,0.000000,False
OsVer,object,17,0.004857,0.000000,False
Wdft_RegionIdentifier,category,15,0.004286,3.414000,False
Census_OSBranch,object,15,0.004286,0.000000,False
SmartScreen,object,12,0.003429,35.758000,False
Census_MDC2FormFactor,object,11,0.003143,0.000000,False
OsPlatformSubRelease,object,9,0.002571,0.000000,False
Census_PowerPlatformRoleName,object,9,0.002571,0.000000,False
Census_OSInstallTypeName,object,9,0.002571,0.000000,False
SkuEdition,object,8,0.002286,0.000000,False
Census_FlightRing,object,7,0.002000,0.000000,False
Census_OSWUAutoUpdateOptionsName,object,6,0.001714,0.000000,False
Census_ActivationChannel,object,6,0.001714,0.000000,False
Platform,object,4,0.001143,0.000000,False
Census_PrimaryDiskTypeName,object,4,0.001143,0.142286,False
Census_ProcessorManufacturerIdentifier,category,4,0.001143,0.468571,False
Census_GenuineStateName,object,4,0.001143,0.000000,False
Processor,object,3,0.000857,0.000000,False
Census_DeviceFamily,object,3,0.000857,0.000000,False
Census_ProcessorClass,category,3,0.000857,99.584571,False
Census_OSArchitecture,object,3,0.000857,0.000000,False
ProductName,object,2,0.000571,0.000000,False
PuaMode,category,1,0.000286,99.974571,False

### 3.1. Null handling class and functions

In [77]:
#This functions helps us check the impact of a column on the target variable, both for null values and for the different values of the column.

def check_signal(df, col, target=target):
    print("Value counts:")
    print(df[col].value_counts(dropna=False, normalize=True))
    
    print("\nNull impact:")
    print(df.groupby(df[col].isnull())[target].mean())
    
    print("\nValue impact:")
    print(df.groupby(col)[target].mean().sort_values())

In [78]:
class DataCleaner:
    
    def __init__(self, df):
        self.df = df.copy()
        self.summary = None
        self.update_summary()
        
        # Lists to track treated columns
        self.fill_constant_list = []
        self.fill_mean_list = []
        self.fill_median_list = []
        self.missing_indicator_list = []
        self.dropped_columns = []
        self.dropped_nanRows_columns = []
        
    def update_summary(self):
        self.summary = pd.DataFrame({
            "dtype": self.df.dtypes,
            "null_count": self.df.isnull().sum(),
            "pct_nulls": self.df.isnull().mean() * 100,
            "unique_values": self.df.nunique()
        })
        
        self.summary = self.summary.sort_values("pct_nulls", ascending=False)
    
    
    def show_nulls(self):
        return self.summary[self.summary["null_count"] > 0]
    
    def show_all(self):
        return self.summary
    
    def drop_columns(self, cols):
        self.df.drop(columns=cols, inplace=True)
        self.dropped_columns.append(cols)
        print(f"Dropped columns: {cols}")
        self.update_summary()
        
    def drop_nanRows(self, cols):
        self.df.dropna(subset=cols, inplace=True)
        self.dropped_nanRows_columns.append(cols)
        print(f"Columns which rows with nulls are dropped: {cols}")
        self.update_summary()
        
    def fill_with_constant(self, col, value="Missing"):
        s = self.df[col]
        if isinstance(s.dtype, pd.CategoricalDtype):
            if value not in s.cat.categories:
                self.df[col] = s.cat.add_categories([value])
                self.df[col] = self.df[col].fillna(value)
                self.fill_constant_list.append(col)
        else:
            self.df[col] = s.fillna(value)
            self.fill_constant_list.append(col)
        print(f"Filled nulls in columns '{col}' with constant value: {value}")
        self.update_summary()
        
    def fill_with_mean(self, col):
        self.df[col] = self.df[col].fillna(self.df[col].mean())
        self.fill_mean_list.append(col)
        self.update_summary()
        
    def fill_with_median(self, col):
        self.df[col] = self.df[col].fillna(self.df[col].median())
        self.fill_median_list.append(col)
        self.update_summary()
        
    def add_missing_indicator(self, col):
        self.df[f"{col}_missing"] = self.df[col].isnull().astype(int)
        self.missing_indicator_list.append(col)
        self.update_summary()
        
    def get_data(self):
        return self.df

In [79]:
cleaner = DataCleaner(df_train)

In [80]:
cleaner.show_nulls()

,dtype,null_count,pct_nulls,unique_values
PuaMode,category,349911,99.974571,1
Census_ProcessorClass,category,348546,99.584571,3
DefaultBrowsersIdentifier,float64,333127,95.179143,469
Census_IsFlightingInternal,float64,290634,83.038286,2
Census_InternalBatteryType,object,249042,71.154857,27
Census_ThresholdOptIn,float64,222746,63.641714,2
Census_IsWIMBootEnabled,float64,222456,63.558857,1
SmartScreen,object,125153,35.758000,12
OrganizationIdentifier,category,108288,30.939429,43
SMode,float64,20910,5.974286,2
CityIdentifier,float64,12691,3.626000,31181
Wdft_RegionIdentifier,float64,11949,3.414000,15
Wdft_IsGamer,float64,11949,3.414000,2
Census_InternalBatteryNumberOfCharges,float64,10511,3.003143,4031
Census_FirmwareManufacturerIdentifier,float64,7254,2.072571,276
Census_FirmwareVersionIdentifier,float64,6345,1.812857,20897
Census_IsFlightsDisabled,float64,6241,1.783143,2
Census_OEMModelIdentifier,float64,4025,1.150000,33296
Census_OEMNameIdentifier,float64,3740,1.068571,1406
Firewall,float64,3615,1.032857,2
Census_TotalPhysicalRAM,float64,3139,0.896857,449
Census_IsAlwaysOnAlwaysConnectedCapable,float64,2814,0.804000,2
Census_OSInstallLanguageIdentifier,float64,2335,0.667143,39
IeVerIdentifier,float64,2232,0.637714,167
Census_PrimaryDiskTotalCapacity,float64,2083,0.595143,906
Census_SystemVolumeTotalCapacity,float64,2083,0.595143,112810
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,1869,0.534000,483
Census_InternalPrimaryDisplayResolutionHorizontal,float64,1867,0.533429,374
Census_InternalPrimaryDisplayResolutionVertical,float64,1867,0.533429,420
Census_ProcessorModelIdentifier,float64,1642,0.469143,2127
Census_ProcessorManufacturerIdentifier,float64,1640,0.468571,4
Census_ProcessorCoreCount,float64,1640,0.468571,27
AVProductsEnabled,float64,1351,0.386000,5
AVProductsInstalled,float64,1351,0.386000,5
AVProductStatesIdentifier,float64,1351,0.386000,4466
IsProtected,float64,1345,0.384286,2
RtpStateBitfield,float64,1290,0.368571,7
Census_IsVirtualDevice,float64,636,0.181714,2
Census_PrimaryDiskTypeName,object,498,0.142286,4
UacLuaenable,float64,431,0.123143,5
Census_ChassisTypeName,object,28,0.008000,33
GeoNameIdentifier,float64,13,0.003714,263
OsBuildLab,object,1,0.000286,431

### 3.2. Borrado de columnas con >95% nulos y filas de columnas con <0.5% nulos

In [81]:
def null_handling(df, high_thresh=95, low_thresh=0.5):

    nulls = df.isnull().sum()
    nulls_df = pd.DataFrame(nulls, columns=["nulls_count"])
    nulls_df["pct_nulls"] = nulls_df["nulls_count"] / df.shape[0] * 100
    nulls_df["unique"] = df.nunique()

    # Columns to drop (>95% nulls)
    high_null_cols = nulls_df[nulls_df["pct_nulls"] > high_thresh].index.tolist()

    # Columns where we drop rows (<0.5% nulls)
    low_null_cols = nulls_df[
        (nulls_df["pct_nulls"] > 0) & 
        (nulls_df["pct_nulls"] < low_thresh)
    ].index.tolist()

    # Drop high-null columns
    #df_nonullcolumns = df.drop(columns=high_null_cols)

    # Drop rows with nulls in low-null columns
    #df_out = df_nonullcolumns.dropna(subset=low_null_cols)

    return high_null_cols, low_null_cols

In [82]:
cols2drop_list, nullrowdrop_cols = null_handling(df_train)
print("Columns to drop due to high null percentage:", cols2drop_list)
print("Columns where rows are dropped due to low null volume:", nullrowdrop_cols)

Columns to drop due to high null percentage: ['DefaultBrowsersIdentifier', 'PuaMode', 'Census_ProcessorClass']
Columns where rows are dropped due to low null volume: ['RtpStateBitfield', 'AVProductStatesIdentifier', 'AVProductsInstalled', 'AVProductsEnabled', 'GeoNameIdentifier', 'OsBuildLab', 'IsProtected', 'UacLuaenable', 'Census_ProcessorCoreCount', 'Census_ProcessorManufacturerIdentifier', 'Census_ProcessorModelIdentifier', 'Census_PrimaryDiskTypeName', 'Census_ChassisTypeName', 'Census_IsVirtualDevice']

In [83]:
cleaner.drop_columns(cols2drop_list)
cleaner.drop_nanRows(nullrowdrop_cols)

Dropped columns: ['DefaultBrowsersIdentifier', 'PuaMode', 'Census_ProcessorClass']
Columns which rows with nulls are dropped: ['RtpStateBitfield', 'AVProductStatesIdentifier', 'AVProductsInstalled', 'AVProductsEnabled', 'GeoNameIdentifier', 'OsBuildLab', 'IsProtected', 'UacLuaenable', 'Census_ProcessorCoreCount', 'Census_ProcessorManufacturerIdentifier', 'Census_ProcessorModelIdentifier', 'Census_PrimaryDiskTypeName', 'Census_ChassisTypeName', 'Census_IsVirtualDevice']

In [84]:
cleaner.show_nulls()

,dtype,null_count,pct_nulls,unique_values
Census_IsFlightingInternal,float64,285465,82.937721,2
Census_InternalBatteryType,object,244534,71.045812,27
Census_ThresholdOptIn,float64,218670,63.531401,2
Census_IsWIMBootEnabled,float64,218389,63.449761,1
SmartScreen,object,122449,35.575783,12
OrganizationIdentifier,category,106537,30.952782,43
SMode,float64,20589,5.981836,2
CityIdentifier,float64,12473,3.623849,30894
Wdft_RegionIdentifier,float64,11064,3.214485,15
Wdft_IsGamer,float64,11064,3.214485,2
Census_InternalBatteryNumberOfCharges,float64,8673,2.519815,4016
Census_FirmwareManufacturerIdentifier,float64,5602,1.627580,273
Census_FirmwareVersionIdentifier,float64,4697,1.364645,20745
Census_IsFlightsDisabled,float64,4420,1.284167,2
Census_OEMModelIdentifier,float64,3473,1.009030,32952
Census_OEMNameIdentifier,float64,3192,0.927389,1391
Firewall,float64,3189,0.926518,2
IeVerIdentifier,float64,2203,0.640050,158
Census_OSInstallLanguageIdentifier,float64,2179,0.633077,39
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,1639,0.476188,480
Census_InternalPrimaryDisplayResolutionVertical,float64,1637,0.475607,394
Census_InternalPrimaryDisplayResolutionHorizontal,float64,1637,0.475607,350
Census_TotalPhysicalRAM,float64,1626,0.472411,429
Census_IsAlwaysOnAlwaysConnectedCapable,float64,1330,0.386412,2
Census_SystemVolumeTotalCapacity,float64,652,0.189429,111853
Census_PrimaryDiskTotalCapacity,float64,652,0.189429,813

### 3.3. Columnas con >30% y <95% nulos

#### Census_IsFlightingInternal: it is a property of the Operating System's "Device Census" service, not a setting you toggle to change how Defender works, due it's high null pct and little difference in target mean between '1' (2 values), '0' and 'missing' we drop it.

In [85]:
check_signal(df_train, 'Census_IsFlightingInternal')

Value counts:
Census_IsFlightingInternal
NaN    0.830383
0.0    0.169614
1.0    0.000003
Name: proportion, dtype: float64

Null impact:
Census_IsFlightingInternal
False    0.485935
True     0.502759
Name: HasDetections, dtype: float64

Value impact:
Census_IsFlightingInternal
1.0    0.000000
0.0    0.485943
Name: HasDetections, dtype: float64

In [86]:
cleaner.drop_columns(['Census_IsFlightingInternal'])

Dropped columns: ['Census_IsFlightingInternal']

#### Drop Census_InternalBatteryType: self explanatory. Categorical variable that will have the Nan's as 'missing' category. Pero se puede eliminar (tipo de batería no indicará malware)

In [87]:
#Add missing category
df_train['Census_InternalBatteryType'].value_counts(dropna = False, normalize = True)

Census_InternalBatteryType
NaN     0.711549
lion    0.226729
li-i    0.027700
#       0.020306
lip     0.006626
liio    0.003537
li p    0.000969
li      0.000734
nimh    0.000577
real    0.000311
bq20    0.000294
pbac    0.000257
vbox    0.000186
lgi0    0.000051
unkn    0.000040
lipo    0.000034
lhp0    0.000023
ram     0.000014
4cel    0.000011
lipp    0.000009
ithi    0.000009
batt    0.000009
bad     0.000006
a132    0.000006
virt    0.000006
icp3    0.000003
3ion    0.000003
lgl0    0.000003
Name: proportion, dtype: float64

In [88]:
check_signal(df_train, 'Census_InternalBatteryType')

Value counts:
Census_InternalBatteryType
NaN     0.711549
lion    0.226729
li-i    0.027700
#       0.020306
lip     0.006626
liio    0.003537
li p    0.000969
li      0.000734
nimh    0.000577
real    0.000311
bq20    0.000294
pbac    0.000257
vbox    0.000186
lgi0    0.000051
unkn    0.000040
lipo    0.000034
lhp0    0.000023
ram     0.000014
4cel    0.000011
lipp    0.000009
ithi    0.000009
batt    0.000009
bad     0.000006
a132    0.000006
virt    0.000006
icp3    0.000003
3ion    0.000003
lgl0    0.000003
Name: proportion, dtype: float64

Null impact:
Census_InternalBatteryType
False    0.485331
True     0.505814
Name: HasDetections, dtype: float64

Value impact:
Census_InternalBatteryType
3ion    0.000000
4cel    0.000000
batt    0.000000
virt    0.000000
ram     0.200000
vbox    0.230769
lhp0    0.250000
bq20    0.252427
ithi    0.333333
lipo    0.416667
nimh    0.420792
li      0.443580
liio    0.464459
pbac    0.466667
lion    0.481104
li-i    0.483136
li p    0.486726
a132    0.500000
bad     0.500000
unkn    0.500000
real    0.504587
#       0.529478
lip     0.545063
lgi0    0.555556
lipp    0.666667
icp3    1.000000
lgl0    1.000000
Name: HasDetections, dtype: float64

In [89]:
cleaner.fill_with_constant('Census_InternalBatteryType', value="Missing")

Filled nulls in columns 'Census_InternalBatteryType' with constant value: Missing

#### Census_ThresholdOptIn can be dropped, it is only an indicator of data collection not a security indicator
Is an internal registry value used by Windows to manage your participation in Windows Insider "Census" data collection. It is not a standard security setting within the Windows Defender/Security interface that you "opt-in" to for better protection.
Instead, this value tracks whether your device meets the "threshold" for certain diagnostic and telemetry reporting required for Insider preview builds of Windows.

In [90]:
check_signal(df_train, 'Census_ThresholdOptIn')

Value counts:
Census_ThresholdOptIn
NaN    0.636417
0.0    0.363489
1.0    0.000094
Name: proportion, dtype: float64

Null impact:
Census_ThresholdOptIn
False    0.490020
True     0.505553
Name: HasDetections, dtype: float64

Value impact:
Census_ThresholdOptIn
0.0    0.490013
1.0    0.515152
Name: HasDetections, dtype: float64

In [91]:
cleaner.drop_columns(['Census_ThresholdOptIn'])

Dropped columns: ['Census_ThresholdOptIn']

#### Census_IsWIMBootEnabled can be dropped as there is only missing or '0' values and there is no meaningful separation when referred to the target

In [92]:
check_signal(df_train, 'Census_IsWIMBootEnabled')

Value counts:
Census_IsWIMBootEnabled
NaN    0.635589
0.0    0.364411
Name: proportion, dtype: float64

Null impact:
Census_IsWIMBootEnabled
False    0.490027
True     0.505570
Name: HasDetections, dtype: float64

Value impact:
Census_IsWIMBootEnabled
0.0    0.490027
Name: HasDetections, dtype: float64

In [93]:
cleaner.drop_columns(['Census_IsWIMBootEnabled'])

Dropped columns: ['Census_IsWIMBootEnabled']

#### SmartScreen. Categorical variable that will have the Nan's as 'missing' category.

In [94]:
#Add missing category
df_train['SmartScreen'].value_counts(dropna = False, normalize = True)

SmartScreen
RequireAdmin    0.482746
NaN             0.357580
ExistsNotSet    0.117029
Off             0.020803
Warn            0.015063
Prompt          0.003934
Block           0.002517
off             0.000140
On              0.000106
&#x02;          0.000037
&#x01;          0.000026
on              0.000017
requireadmin    0.000003
Name: proportion, dtype: float64

In [95]:
cleaner.fill_with_constant('SmartScreen', value="Missing")

Filled nulls in columns 'SmartScreen' with constant value: Missing

#### OrganizationIdentifier:  ID for the organization the machine belongs in, organization ID is mapped to both specific companies and broad industries
Column will be treated as categorical and missing values will turn to '-1'.

In [96]:
check_signal(df_train, 'OrganizationIdentifier')

Value counts:
OrganizationIdentifier
 27.0    0.469929
NaN      0.309394
 18.0    0.197289
 48.0    0.007357
 50.0    0.005120
 11.0    0.002074
 37.0    0.002066
 49.0    0.001414
 46.0    0.001277
 14.0    0.000534
 32.0    0.000437
 36.0    0.000423
 33.0    0.000366
 52.0    0.000337
 2.0     0.000309
 5.0     0.000209
 40.0    0.000191
 28.0    0.000183
 4.0     0.000160
 10.0    0.000143
 51.0    0.000103
 1.0     0.000089
 20.0    0.000071
 8.0     0.000066
 47.0    0.000057
 3.0     0.000051
 22.0    0.000046
 39.0    0.000043
 6.0     0.000043
 31.0    0.000037
 21.0    0.000029
 16.0    0.000023
 42.0    0.000023
 19.0    0.000020
 7.0     0.000017
 44.0    0.000017
 29.0    0.000014
 26.0    0.000011
 43.0    0.000009
 41.0    0.000006
 45.0    0.000006
 23.0    0.000003
 35.0    0.000003
 25.0    0.000003
 17.0    0.000000
Name: proportion, dtype: float64

Null impact:
OrganizationIdentifier
False    0.501183
True     0.497054
Name: HasDetections, dtype: float64

Value impact:
OrganizationIdentifier
25.0    0.000000
23.0    0.000000
16.0    0.250000
19.0    0.285714
21.0    0.300000
43.0    0.333333
22.0    0.375000
1.0     0.387097
3.0     0.388889
6.0     0.400000
2.0     0.407407
10.0    0.420000
32.0    0.424837
4.0     0.446429
47.0    0.450000
33.0    0.453125
28.0    0.453125
37.0    0.457815
31.0    0.461538
14.0    0.465241
5.0     0.465753
51.0    0.472222
49.0    0.480808
40.0    0.492537
27.0    0.498434
7.0     0.500000
44.0    0.500000
45.0    0.500000
41.0    0.500000
18.0    0.505177
46.0    0.514541
48.0    0.514951
52.0    0.516949
20.0    0.520000
11.0    0.526171
39.0    0.533333
36.0    0.587838
29.0    0.600000
50.0    0.612723
8.0     0.739130
42.0    0.750000
26.0    0.750000
35.0    1.000000
17.0         NaN
Name: HasDetections, dtype: float64

C:\Users\Jon Mikel.DESKTOP-Q1JUAAF\AppData\Local\Temp\ipykernel_14656\2969254655.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(df.groupby(col)[target].mean().sort_values())

In [97]:
cleaner.fill_with_constant('OrganizationIdentifier', value="-1")

Filled nulls in columns 'OrganizationIdentifier' with constant value: -1

### 3.4. Columnas <30% nulos

In [98]:
cleaner.show_nulls()

,dtype,null_count,pct_nulls,unique_values
SMode,float64,20589,5.981836,2
CityIdentifier,float64,12473,3.623849,30894
Wdft_RegionIdentifier,float64,11064,3.214485,15
Wdft_IsGamer,float64,11064,3.214485,2
Census_InternalBatteryNumberOfCharges,float64,8673,2.519815,4016
Census_FirmwareManufacturerIdentifier,float64,5602,1.627580,273
Census_FirmwareVersionIdentifier,float64,4697,1.364645,20745
Census_IsFlightsDisabled,float64,4420,1.284167,2
Census_OEMModelIdentifier,float64,3473,1.009030,32952
Census_OEMNameIdentifier,float64,3192,0.927389,1391
Firewall,float64,3189,0.926518,2
IeVerIdentifier,float64,2203,0.640050,158
Census_OSInstallLanguageIdentifier,float64,2179,0.633077,39
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,1639,0.476188,480
Census_InternalPrimaryDisplayResolutionVertical,float64,1637,0.475607,394
Census_InternalPrimaryDisplayResolutionHorizontal,float64,1637,0.475607,350
Census_TotalPhysicalRAM,float64,1626,0.472411,429
Census_IsAlwaysOnAlwaysConnectedCapable,float64,1330,0.386412,2
Census_SystemVolumeTotalCapacity,float64,652,0.189429,111853
Census_PrimaryDiskTotalCapacity,float64,652,0.189429,813

#### Boolean columns Fillna to 0
SMode: Dados los resultados, aun con pocos valores '1', indican mucha menor media de detección que los '0'. Se decide imputar los missing values de SMode con la moda (0) dado que tienen una media parecida al '0'.

Wdft_IsGamer: mayor detección de malware en Gamer = '1', missing se asigna a moda '0'.

Census_IsAlwaysOnAlwaysConnectedCapable: menor detección de malware en valor = '1', missing se asigna a moda '0'.

Firewall: no hay tendencia clara, missing se asigna a moda '0'.

In [99]:
check_signal(df_train, 'SMode')

Value counts:
SMode
0.0    0.939809
NaN    0.059743
1.0    0.000449
Name: proportion, dtype: float64

Null impact:
SMode
False    0.505102
True     0.418125
Name: HasDetections, dtype: float64

Value impact:
SMode
1.0    0.197452
0.0    0.505249
Name: HasDetections, dtype: float64

In [100]:
#Dados los resultados, se decide imputar los missing values de SMode con la moda (0)
cleaner.fill_with_constant('SMode', value = 0)

Filled nulls in columns 'SMode' with constant value: 0

In [101]:
check_signal(df_train, 'Wdft_IsGamer')

Value counts:
Wdft_IsGamer
0.0    0.69138
1.0    0.27448
NaN    0.03414
Name: proportion, dtype: float64

Null impact:
Wdft_IsGamer
False    0.499067
True     0.523642
Name: HasDetections, dtype: float64

Value impact:
Wdft_IsGamer
0.0    0.480761
1.0    0.545176
Name: HasDetections, dtype: float64

In [102]:
cleaner.fill_with_constant('Wdft_IsGamer', value = 0)

Filled nulls in columns 'Wdft_IsGamer' with constant value: 0

In [103]:
check_signal(df_train, 'Census_IsAlwaysOnAlwaysConnectedCapable')

Value counts:
Census_IsAlwaysOnAlwaysConnectedCapable
0.0    0.935211
1.0    0.056749
NaN    0.008040
Name: proportion, dtype: float64

Null impact:
Census_IsAlwaysOnAlwaysConnectedCapable
False    0.499732
True     0.521322
Name: HasDetections, dtype: float64

Value impact:
Census_IsAlwaysOnAlwaysConnectedCapable
1.0    0.369953
0.0    0.507607
Name: HasDetections, dtype: float64

In [104]:
cleaner.fill_with_constant('Census_IsAlwaysOnAlwaysConnectedCapable', value = 0)

Filled nulls in columns 'Census_IsAlwaysOnAlwaysConnectedCapable' with constant value: 0

In [105]:
check_signal(df_train, 'Firewall')

Value counts:
Firewall
1.0    0.967997
0.0    0.021674
NaN    0.010329
Name: proportion, dtype: float64

Null impact:
Firewall
False    0.500010
True     0.489903
Name: HasDetections, dtype: float64

Value impact:
Firewall
0.0    0.491959
1.0    0.500190
Name: HasDetections, dtype: float64

In [106]:
cleaner.fill_with_constant('Firewall', value = 0)

Filled nulls in columns 'Firewall' with constant value: 0

#### Boolean column Census_IsFlightsDisabled: solo 6 values ='1'. Se elimina.

In [107]:
check_signal(df_train, 'Census_IsFlightsDisabled')

Value counts:
Census_IsFlightsDisabled
0.0    0.982151
NaN    0.017831
1.0    0.000017
Name: proportion, dtype: float64

Null impact:
Census_IsFlightsDisabled
False    0.499804
True     0.505528
Name: HasDetections, dtype: float64

Value impact:
Census_IsFlightsDisabled
1.0    0.000000
0.0    0.499812
Name: HasDetections, dtype: float64

In [108]:
cleaner.drop_columns('Census_IsFlightsDisabled')

Dropped columns: Census_IsFlightsDisabled

In [109]:
cleaner.show_nulls()

,dtype,null_count,pct_nulls,unique_values
CityIdentifier,float64,12473,3.623849,30894
Wdft_RegionIdentifier,float64,11064,3.214485,15
Census_InternalBatteryNumberOfCharges,float64,8673,2.519815,4016
Census_FirmwareManufacturerIdentifier,float64,5602,1.627580,273
Census_FirmwareVersionIdentifier,float64,4697,1.364645,20745
Census_OEMModelIdentifier,float64,3473,1.009030,32952
Census_OEMNameIdentifier,float64,3192,0.927389,1391
IeVerIdentifier,float64,2203,0.640050,158
Census_OSInstallLanguageIdentifier,float64,2179,0.633077,39
Census_InternalPrimaryDiagonalDisplaySizeInInches,float64,1639,0.476188,480
Census_InternalPrimaryDisplayResolutionVertical,float64,1637,0.475607,394
Census_InternalPrimaryDisplayResolutionHorizontal,float64,1637,0.475607,350
Census_TotalPhysicalRAM,float64,1626,0.472411,429
Census_SystemVolumeTotalCapacity,float64,652,0.189429,111853
Census_PrimaryDiskTotalCapacity,float64,652,0.189429,813

In [110]:
cleaner.dropped_columns

[['DefaultBrowsersIdentifier', 'PuaMode', 'Census_ProcessorClass'],
 ['Census_IsFlightingInternal'],
 ['Census_ThresholdOptIn'],
 ['Census_IsWIMBootEnabled'],
 'Census_IsFlightsDisabled']

In [111]:
cleaner.fill_constant_list

['Census_InternalBatteryType',
 'SmartScreen',
 'OrganizationIdentifier',
 'SMode',
 'Wdft_IsGamer',
 'Census_IsAlwaysOnAlwaysConnectedCapable',
 'Firewall']

### 2.2. Tratado de las demás columnas con nulos

#### 2.2.1. Para el valor nulo de la potencia, al tratarse de una fila con un único nulo, procedemos a reemplazar el nulo con la media de potencia del modelo en cuestión (525)
También se detecta un coche con potencia 0 y se trata como nulo, asignando la media de potencia de su modelo "X1"

## 4. Análisis univariable

### 3.1. DataCleaner (Null-focused) class

### 3.2. Feature Analyzer (target-aware) class

In [ ]:
class FeatureAnalyzer:
    
    def __init__(self, df, target):
        self.df = df
        self.target = target
        
    def compute_numeric_correlations(self):
        numeric_cols = self.df.select_dtypes(include=np.number).columns
        numeric_cols = numeric_cols.drop(self.target, errors='ignore')
        
        correlations = {}
        
        for col in numeric_cols:
            correlations[col] = self.df[col].corr(self.df[self.target])
            
        return pd.Series(correlations).sort_values(key=abs, ascending=False)
    
    
    def compute_categorical_impact(self):
        cat_cols = self.df.select_dtypes(include=['object', 'category']).columns
        
        impact_scores = {}
        
        for col in cat_cols:
            means = self.df.groupby(col)[self.target].mean()
            impact = means.max() - means.min()
            impact_scores[col] = impact
            
        return pd.Series(impact_scores).sort_values(ascending=False)
    
    
    def full_report(self):
        
        numeric_corr = self.compute_numeric_correlations()
        categorical_impact = self.compute_categorical_impact()
        
        return {
            "numeric_correlation": numeric_corr,
            "categorical_impact": categorical_impact
        }

### 3.1. Columnas de fechas a mes y año (todos los días son 1) y adición de columna meses_registro_a_venta (diferencia de meses entre registro y venta, incluyendo su missing)

In [ ]:
df4 = df3.copy()

In [ ]:
df4['meses_registro_a_venta']=(
    (df4['fecha_venta'].dt.year-df4['fecha_registro'].dt.year)*12
    +df4['fecha_venta'].dt.month-df4['fecha_registro'].dt.month)
df4['meses_registro_a_venta'+'_missing']=df4['fecha_registro_missing']

In [ ]:
for col in ['fecha_registro', 'fecha_venta']:
  df4[col + '_month'] = df4[col].dt.month
  df4[col + '_year'] = df4[col].dt.year

  del(df4[col])

In [ ]:
df4.head(10)

###3.2. Análisis univariable por tipo

* 'km' tiene 1 valor negativo y un valor de 1 millón (outliers)
* 'modelo' tiene info de categorías de coche según el modelo  
* 'gps' tiene sólo 328 valores False, poca info en esta columna
*   'fecha_venta' tiene valores entre enero y septiembre de 2018, a expeción de 4 filas
* 'fecha_registro' tiene la mayor parte de los valores no nulos entre 2012 y 2014
* 'tipo_gasolina' tiene únicamente 11 valores que no son ni diésel ni gasolina. Se decide eliminar estas 11 filas y sustituir la columna por una llamada 'is_petrol' con valor 1 si el coche es gasolina y 0 si es diesel.

In [ ]:
for col in ['volante_regulable', 'elevalunas_electrico']:
  df4[col] = df4[col].astype(bool)

In [ ]:
for i in df4:
  print(i,df4[i].dtype.kind)

In [ ]:
for i in df4:
  if (df4[i].dtype.kind == "O") or(df4[i].dtype.kind == "b"):
    print(i,'\n', df4[i].value_counts(), '\n')
  elif (df4[i].dtype.kind=="f") or (df4[i].dtype.kind=="i"):
    print(df4.hist(i))

In [ ]:
df4['fecha_venta_year'].hist()

In [ ]:
df4.drop(df4.loc[df4['fecha_venta_year']<2018].index, axis=0,inplace=True)

In [ ]:
df4['km'].describe()

In [ ]:
sns.boxplot(x=df4['km'])

In [ ]:
df4.loc[df4['km']<1000]

In [ ]:
df4.drop(df4.loc[df4['km']<0].index, axis=0, inplace=True)

In [ ]:
df4.loc[df4['km']<0]

In [ ]:
df4.drop(df4.loc[df4['km']>800000].index, axis=0, inplace=True)

In [ ]:
df4.loc[df4['km']>800000]

In [ ]:
df4['tipo_gasolina'].value_counts()

In [ ]:
#Borramos los 11 coches que no son ni petrol ni diesel
df4.drop(df4.loc[(df4['tipo_gasolina']=='hybrid_petrol')|(df4['tipo_gasolina']=='electro')].index, axis=0, inplace=True)

In [ ]:
df4['is_petrol'] = df4['tipo_gasolina'].str.contains('petrol')

In [ ]:
#Borramos la columna 'tipo_gasolina' ya que su info está en 'is_petrol'
del(df4['tipo_gasolina'])

In [ ]:
df4.head()

###3.3. Modelo: al revisar el significado de los números y letras en los modelos de BMW, se decide dividir el modelo en columnas: Series, Model_Class (la cual estudiaremos su variabilidad e info que aporta: X1/X3/X5... gran/Active, etc)

In [ ]:
pd.set_option('display.max_rows', 76)

In [ ]:
df4['modelo'].value_counts()

In [ ]:
df5 = df4.copy()

In [ ]:
import re

def get_series(model):
    model = model.strip()

    if model.startswith("X"):
        return "X"

    if model.startswith("Z"):
        return "Z"

    if model.startswith("i"):
        return "i"

    if model.startswith("M"):
        return "M"

    match = re.match(r"(\d)", model)
    if match:
        return f"{match.group(1)} Series"

    return "Unknown"

In [ ]:
df5['Series']=df5['modelo'].apply(get_series)

In [ ]:
df5.loc[df5['modelo']=="ActiveHybrid 5",'Series']="5 Series"

In [ ]:
df5.loc[df5['modelo']=="M135", 'Series']="1 Series" #Se ha comprobado que este modelo es de 1 Series y no M

In [ ]:
df5.loc[df5['modelo']=="M235", 'Series']="2 Series" #Se ha comprobado que este modelo es de 2 Series y no M

In [ ]:
df5.loc[df5['modelo']=="Active Tourer"]

In [ ]:
df5['Series'].value_counts()

In [ ]:
df5.loc[df5['Series']=='Unknown','Series'] = '2 Series' #Al ser Tourer es 2 Series (el filtro con 'Active Tourer' en modelo no funcionaba)

In [ ]:
df5['is_gran'] = df5['modelo'].str.contains('Gran')

In [ ]:
df5['is_gran'].sum()

In [ ]:
 #La categoría 'active' sólo tiene 19 coches, no es info representativa
df5['modelo'].str.contains('Active').sum()

In [ ]:
df5.loc[df5['Series']=="X"].groupby('modelo')['precio'].describe() #El Model_Class que muestra variabilidad respecto al target son las X Series, por lo que se hará una columna que marca el modelo X en cuestión (X1,X3,X5,X_Other)

In [ ]:
df5.loc[df5['Series']=="3 Series"].groupby('modelo')['precio'].describe() #El resto de Series con muchas muestras no muestran diferencias significativas entre modelos respecto al target

In [ ]:
df5['X_Model']= df5.apply(lambda x: x['modelo'] if 'X' in x['modelo'] else "NULL", axis=1)

In [ ]:
df5['X_Model'].value_counts()

In [ ]:
#del[df5['modelo']] #Una vez empleada la columna modelo, se puede eliminar para facilitar el aprendizaje

In [ ]:
plt.figure(figsize=(20, 6))
sns.violinplot(x=df5['Series'], y=df5['precio'])

##4. Análisis de correlación inicial
* El GPS se relaciona con otras variables pero no con el precio.
* La potencia está relacionada con alerta_lim_velocidad, bluetooth y aire_acondicionado, además de con el target.
* Los km con el target (inversamente) y poco con gps.
* Las fechas no muestran info en esta primera correlación. Las fechas de venta se borran.
* La columna 'is_petrol' derivada del tipo de combustible tiene apenas un 0.031 de correlación con el precio.

In [ ]:
df5.info()

In [ ]:
corr = df5.corr(numeric_only = True)

In [ ]:
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
#Al no haber correlación entre fechas de venta y otras variables se decide borrarlas (su info sigue en la columna 'meses_registro_a_venta')
df5.drop(['fecha_venta_month','fecha_venta_year'],axis=1,inplace=True)

##5. Análisis variable vs target

###5.1. Análisis target y creación de columna LOG_precio

In [ ]:
target = "precio"

In [ ]:
df6 = df5.copy()

In [ ]:
df6[target].hist()

In [ ]:
df6['LOG_precio']=np.log10(df6['precio'])

In [ ]:
df6['LOG_precio'].hist()

In [ ]:
sns.boxplot(x=df6['precio'])

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df6.loc[df6['precio']>90000] # Aquí observamos los outliers, podemos borrar las filas con precio superior a 90000

In [ ]:
#La fila del X4 de 103222km es outlier, tiene un valor 5 veces superior a de los demás coches en su modelo y km parecidos
df6.loc[(df6['modelo']=="X4")&(df6['km']>80000)&(df6['potencia']==140)]

In [ ]:
#la fila del X3 de 72515km es outlier, con un valor 9 veces superior a los coches de su modelo y km parecidos
df6.loc[(df6['modelo']=="X3")&(df6['km']<80000)&(df6['potencia']==135)]

In [ ]:
#Eliminamos los outliers de precio una vez comprobado que con alta probabilidad los precios son incorrectos
df6.drop(df6.loc[df6['precio']>90000].index, axis=0, inplace = True)

In [ ]:
df6.loc[df6['precio']>90000]

In [ ]:
#En lo referido a precios menores a 400€, se decide dejarlos ya que podrían ser coches con daños, piezas con cambio imperativo etc
df6.loc[df6['precio']<400]

###5.2. Relación de target con las variables numéricas:

In [ ]:
for i in df6:
  if (df6[i].dtype.kind == 'i') | (df6[i].dtype.kind == 'f'):
    print(i)

In [ ]:
df6.info()

####km está inversamente relacionado con el target

In [ ]:
sns.scatterplot(x=df6['km'], y=df6["precio"])

####La potencia está relacionada directamente con el precio

In [ ]:
sns.scatterplot(x=df6['potencia'], y=df6["precio"])

####Mediante los valores no nulos de meses_registro_a_venta está inversamente relacionada con el precio
Cuantos menos meses hayan transcurrido entre registro y venta, más caro es el coche. Aunque se podría inducir que cuanto más nuevo es el coche más caro es, no podemos concluir por la fecha de registro que el coche se ha fabricado en ese año.

In [ ]:
sns.scatterplot(x=df6.loc[df6['meses_registro_a_venta_missing']==0,'meses_registro_a_venta'], y=df6["precio"])

####La fecha_registro_year está relacionada directamente con el precio, cuanto más nuevo más vale

In [ ]:
sns.scatterplot(x=df6.loc[df6['fecha_registro_missing']==0,'fecha_registro_year'], y=df6["precio"])

In [ ]:
reg_no_miss = (df6['fecha_registro_missing']==0)
reg_corr = df6.loc[reg_no_miss,['fecha_registro_year',target]].corr()
diff_corr = df6.loc[reg_no_miss,['meses_registro_a_venta',target]].corr()
diff_reg_corr = df6.loc[reg_no_miss,['meses_registro_a_venta','fecha_registro_year']].corr()

print("La correlación fecha_registro_year con target es: ", reg_corr)
print("La correlación meses_registro_a_venta con target es: ", diff_corr)
print("La correlación meses_registro_a_venta con fecha_registro_year es: ", diff_reg_corr)

In [ ]:
#Dada la mayor correlación entre fecha_registro_year y target que la de la columna 'meses_registro_a_venta',
#decidimos borrar las columnas calculadas ya que no aportan información adicional respecto al target
df6.drop(['meses_registro_a_venta','meses_registro_a_venta_missing','fecha_registro_month'],axis=1,inplace=True)

###5.3. Relación de target con las variables categóricas y booleanas:

####Cada Series tiene rangos de precio diferentes

In [ ]:
df6.groupby('Series')['precio'].describe()

####Color: no se aprecian diferencias notables

In [ ]:
df6.groupby('color')['precio'].describe()

####is_petrol: los coches de gasolina pueden resultar algo más baratos, pero disponemos de muy pocos datos (<4%)

In [ ]:
df6.groupby('is_petrol')['precio'].describe()

####tipo_coche: se aprecian precios medios diferentes según el tipo de coche

También podrían estar relacionados con la columna Series, pero salvo en el tipo SUV, no se aprecia una relación directa entre columnas (un tipo perteneciendo a una Serie o viceversa)

In [ ]:
df6.groupby('tipo_coche')['precio'].describe()

In [ ]:
df6.loc[df6['tipo_coche']!='No_tipo'].groupby('Series')['tipo_coche'].describe()

In [ ]:
df6.loc[df6['tipo_coche']!='No_tipo'].groupby('tipo_coche')['Series'].describe()

####volante_regulable está directamente relacionado con el target

In [ ]:
sns.violinplot(x=df6['volante_regulable'], y=df6['precio'])

In [ ]:
df6.groupby('volante_regulable')['precio'].describe()

####camara_trasera está directamente relacionado con el target

In [ ]:
df6.groupby('camara_trasera')['precio'].describe()

####elevalunas_electrico está directamente relacionado con el target

In [ ]:
sns.violinplot(x=df6['elevalunas_electrico'], y=df6['precio'])

In [ ]:
df6.groupby('elevalunas_electrico')['precio'].describe()

####gps no tiene relación aparente con el target

In [ ]:
sns.violinplot(x=df6['gps'], y=df6['precio'])

In [ ]:
df6.groupby('gps')['precio'].describe()

###5.4. Relación de target con las variables con columna 'missing':

In [ ]:
#Comprobación de la correlación entre columnas '_missing'. No se aprecia ninguna relación entre ellas
df6[[c for c in df6.columns if c.endswith('_missing')]].corr()

####aire_acondicionado,  está relacionado directamente con el precio
Se revisan los datos teniendo en cuenta la columna que nos indica los datos reales de la columna y a parte los datos de los 'missing'

In [ ]:
df6.loc[df6['aire_acondicionado_missing']==0].groupby('aire_acondicionado')['precio'].describe()

In [ ]:
df6.loc[df6['aire_acondicionado_missing']==1].groupby('aire_acondicionado')['precio'].describe()

####bluetooth: está relacionado directamente con el precio

In [ ]:
df6.loc[df6['bluetooth_missing']!=1].groupby('bluetooth')['precio'].describe()

In [ ]:
df6.loc[df6['bluetooth_missing']!=0].groupby('bluetooth')['precio'].describe()

####alerta_lim_velocidad: está relacionado directamente con el precio

In [ ]:
df6.loc[df6['alerta_lim_velocidad_missing']!=1].groupby('alerta_lim_velocidad')['precio'].describe()

In [ ]:
df6.loc[df6['alerta_lim_velocidad_missing']!=0].groupby('alerta_lim_velocidad')['precio'].describe()

##6. Variables categóricas a numéricas mediante OHE
Nos disponemos a convertir las columnas 'color', 'tipo_coche', 'Series' y 'X_Model'. La columna modelo es eliminada.

In [ ]:
df7 = df6.copy()

In [ ]:
target = ['precio', 'LOG_precio']

In [ ]:
del(df7['modelo'])

In [ ]:
def obtener_lista_variables(dataset):

    lista_numericas=[]
    lista_boolean=[]
    lista_categoricas=[]

    for i in dataset:
        if    (dataset[i].dtype.kind in ("f","i")) and len(dataset[i].unique())!= 2 and i not in target:
              lista_numericas.append(i)
        elif  (dataset[i].dtype.kind in ("f","i","b")) and len(dataset[i].unique())== 2 and i not in target:
              lista_boolean.append(i)
        elif  (dataset[i].dtype.kind == "O") and i not in target:
              lista_categoricas.append(i)

    return lista_numericas, lista_boolean, lista_categoricas

In [ ]:
lista_numericas, lista_boolean, lista_categoricas = obtener_lista_variables(df7)

In [ ]:
lista_numericas

In [ ]:
lista_boolean

In [ ]:
lista_categoricas

####Función ohe_variables_2percent
Para limitar la cantidad de columnas que se crearán en el OHE, agrupamos mediante la siguiente función las categorías que tienen menos del 2% de filas respecto del total. Son agrupadas en la variable 'selected_category' que puede ser una que ya exista o una nueva que agrupe

Con el objetivo de asegurar un correcto funcionamiento se imprime con la ejecución la lista de variables con menos de 2% de valores

In [ ]:
def ohe_variables_2percent(series, selected_category):
  vc = series.value_counts()
  remove_list=[]
  for key in vc.keys():
    if vc.loc[key]<series.count()*0.02:
      remove_list.append(key)
  print(remove_list)
  # Replace categories in remove_list with the selected_category
  modified_series = series.replace(remove_list, selected_category)
  return modified_series

###6.1. 'Color'
Agruparemos los colores minoritarios en 'Other_colors'

In [ ]:
df7['color'].value_counts()

In [ ]:
df7['color'] = ohe_variables_2percent(df7['color'], 'Other_color')

###6.2. 'tipo_coche'
Agruparemos los tipo_coche minoritarios en 'Otro_tipo'

In [ ]:
df7['tipo_coche'] = ohe_variables_2percent(df7['tipo_coche'], 'Otro_tipo')

In [ ]:
df7['tipo_coche'].value_counts()

###6.3. 'Series'
Agruparemos las Series minoritarias en 'Other_Series'

In [ ]:
df7['Series'].value_counts()

In [ ]:
df7['Series'] = ohe_variables_2percent(df7['Series'], 'Other_Series')

In [ ]:
df7['Series'].value_counts()

###6.4. 'X_Model'
Agruparemos los X_Model minoritarias en 'Other_X'

In [ ]:
df7['X_Model'] = ohe_variables_2percent(df7['X_Model'], 'Other_X')

In [ ]:
df7['X_Model'].value_counts()

###6.5. OHE mediante la funcion get_dummies

In [ ]:
df_bmw_prep = pd.get_dummies(data=df7, columns=lista_categoricas, )

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df_bmw_prep.head(10)

In [ ]:
pd.reset_option("display.max_columns")

In [ ]:
df_bmw_prep.info(verbose=False)

##7. Escalado de variables numéricas mediante minmaxscaler y correlación final

In [ ]:
lista_numericas

In [ ]:
MinMax = MinMaxScaler()

###7.1. 'fecha_registro_year' se trata a parte
Al tener la mitad de los años en 1900, perdería la información al estar todos los valores en 0 o cerca de 1. Con el objetivo de destacar los valores reales, se ha decidido escalar los valores reales y representar los valores nulos con 0.

In [ ]:
lista_numericas.remove('fecha_registro_year')

In [ ]:
mask = (df_bmw_prep['fecha_registro_missing'] == 0)
df_bmw_prep.loc[mask, 'fecha_registro_year'] = MinMax.fit_transform(df_bmw_prep.loc[mask, ['fecha_registro_year']])
# df.loc[mask, 'registry_year_scaled'] = scaler.fit_transform(
#     df.loc[mask, ['registry_year']]
# )

In [ ]:
df_bmw_prep.loc[~mask, 'fecha_registro_year'] = 0

In [ ]:
df_bmw_prep['fecha_registro_year'].hist()

###7.2. Tratado de km y potencia

In [ ]:
df_bmw_prep[lista_numericas] = MinMax.fit_transform(df_bmw_prep[lista_numericas])

In [ ]:
df_bmw_prep.head(10)

###7.3. Correlación final

In [ ]:
corr_final = df_bmw_prep.corr(numeric_only = True)

In [ ]:
corr_final.style.background_gradient(cmap='coolwarm')

In [ ]:
corr2 = corr_final.where(np.triu(np.ones(corr_final.shape),k=1).astype(bool)) # Nos quedamos con el triangulo superior

In [ ]:
corr2

In [ ]:
corr3 = corr2.unstack().dropna()

In [ ]:
corr3

In [ ]:
corr4 = corr3.sort_values()

In [ ]:
pd.set_option('display.max_rows', None)

In [ ]:
corr4

In [ ]:
pd.reset_option("display.max_rows")

In [ ]:
corr4.head(20)

In [ ]:
corr4.tail(20)

In [ ]:
corr_long = (
    corr2
    .stack()
    .reset_index()
    .rename(columns={"level_0": "var_1", "level_1": "var_2", 0: "correlation"})
)

In [ ]:
target_corr_long = corr_long[
    (corr_long["var_1"].isin(target)) ^ (corr_long["var_2"].isin(target))
].sort_values(by="correlation")

In [ ]:
target_corr_long.head(10)

In [ ]:
target_corr_long.tail(10)

In [ ]:
target_corr_long.loc[(target_corr_long["var_1"] == "precio")^(target_corr_long["var_2"] == "precio")].tail(10).sort_values("correlation", ascending = False)

In [ ]:
target_corr_long.loc[(target_corr_long["var_1"] == "precio")^(target_corr_long["var_2"] == "precio")].head(10).sort_values("correlation")

In [ ]:
target_corr_long.loc[(target_corr_long["var_1"] == "LOG_precio")^(target_corr_long["var_2"] == "LOG_precio")].tail(10).sort_values("correlation", ascending = False)

In [ ]:
target_corr_long.loc[(target_corr_long["var_1"] == "LOG_precio")^(target_corr_long["var_2"] == "LOG_precio")].head(10).sort_values("correlation")

## 5. Modelling

In [112]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median"))
])

Next Steps:

Finish the version and ID identifiers, if likely_categorical --> transform we will handle later

Drop and handle known columns

Manage the remaining numeric columns assigning mean

Manage categorical assigning 'missing' to string and '-1' to numeric categorical columns
Check with chatty if there could be a limit in columns and if a # of categories check can be done when auto_group_rare_categories can be done

Try first model